# Основи биоинформатике — увод у Python (наставак)

**Тема:** нумеричко рачунање у Python-у уз 'NumPy' + графикa у 'matplotlib'  
**Материјал:** ISLP (Chapter 2, Lab) — изабрани део ('Python'/NumPy/Plotting сегмент)
**Адаптирао:** проф.др.Марко Ђорђевић 
## Увод у нумерички Python ('NumPy')

Настављамо да користимо функционалности које су садржане у пакету `numpy`
(често се каже и *библиотека*). Пакет је збирка 'module'-а који нису нужно део основне `Python`
дистрибуције. Сам назив `numpy` је скраћеница од *numerical Python*.


Да бисмо користили `numpy`, прво морамо да га увеземо (`import`).

In [1]:
import numpy as np 

У претходној линији смо `numpy` 'module' назвали `np` — скраћеница која олакшава куцање и читање кода.

У `numpy`-у, 'array' је општи назив за вишедимензионалну структуру бројева.
Функцијом `np.array()` дефинишемо `x` и `y`, који су једнодимензионални 'array'-и, тј. вектори.

In [6]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

numpy.ndarray

Обратите пажњу: ако сте заборавили да претходно извршите `import numpy as np`, добићете грешку када позовете `np.array()`.
Синтакса `np.array()` показује да је функција део пакета `numpy`, који смо скратили на `np`.

Пошто су `x` и `y` дефинисани помоћу `np.array()`, добијамо „смислен“ резултат када их саберемо.
Упоредите ово са ситуацијом када смо покушали да саберемо две листе без `numpy`-а.

In [3]:
x + y

array([ 7, 13, 12])

У `numpy`-у, матрице се обично представљају као дводимензионални 'array'-и, а вектори као једнодимензионални 'array'-и.
{Иако постоји и `np.matrix()`, доследно ћемо користити `np.array()`.}

Дводимензионални 'array' можемо направити овако.

In [4]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

Објекат `x` има више *атрибута* (енгл. 'attribute'), односно придружених информација.
Да приступимо атрибуту објекта `x`, пишемо `x.attribute`, где `attribute` заменимо именом атрибута.

На пример, атрибуту `ndim` приступамо овако.

In [5]:
x.ndim

2

Излаз показује да је `x` дводимензионални 'array'.  
Слично томе, `x.dtype` је атрибут који описује *тип података* (енгл. 'data type') унутар `x`.
Овде видимо да је `x` састављен од 64-битних целих бројева.

In [6]:
x.dtype

dtype('int64')

Зашто је `x` састављен од целих бројева? Зато што смо у `np.array()` проследили искључиво целе бројеве.
Да смо проследили и децимале, добили бисмо 'array' од *покретних зареза* (енгл. 'floating point'), тј. реалних бројева.

In [7]:
np.array([[1, 2], [3.0, 4]]).dtype


dtype('float64')

Ако укуцате `fun?`, `Python` (тачније IPython у 'Jupyter'-у) ће приказати документацију за функцију `fun`, ако постоји.
Пробајмо то за `np.array()`.

In [8]:
np.array?


Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

Из документације видимо да можемо да направимо 'array' са реалним бројевима тако што у `np.array()` проследимо аргумент `dtype`.

In [9]:
np.array([[1, 2], [3, 4]], float).dtype


dtype('float64')

'Array' `x` је дводимензионалан. Број редова и колона можемо сазнати из његовог атрибута `shape`.

In [10]:
x.shape


(2, 2)

*Метод* (енгл. 'method') је функција која је „везана“ за објекат.
На пример, за 'array' `x`, израз `x.sum()` сабира све елементе користећи метод `sum()` за 'array'-е.
Позив `x.sum()` аутоматски прослеђује `x` као први аргумент том методу.

In [11]:
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

Елементе `x` можемо да саберемо и тако што `x` проследимо као аргумент функцији `np.sum()`.

In [12]:
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

Као још један пример, метод `reshape()` враћа нови 'array' са истим елементима као `x`, али другачијег облика.
То постижемо тако што у `reshape()` проследимо 'tuple', овде `(2, 3)`. Овај 'tuple' каже да желимо дводимензионални 'array' са
$2$ реда и $3$ колоне.
{Као и листе, 'tuple'-ови представљају секвенцу објеката. Зашто нам треба више начина да представимо секвенцу? Постоји више разлика
између 'tuple'-ова и листи, али најважнија je да се елементи 'tuple'-а се не могу мењати (непроменљиви су), док елементи листе могу.}

У наставку, карактер `\n` означава *нови ред*.

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)


beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


Претходни излаз показује да се `numpy` 'array'-и представљају као секвенца *редова*.
Ово се зове *row-major ordering* (распоређивање по врстама), за разлику од *column-major ordering*.

`Python` (и самим тим `numpy`) користи индексирање које почиње од 0.
Зато, да бисмо приступили горњем левом елементу `x_reshape`, пишемо `x_reshape[0,0]`.

In [14]:
x_reshape[0, 0] 

np.int64(1)

Слично томе, `x_reshape[1,2]` даје елемент у другом реду и трећој колони матрице `x_reshape`.

In [15]:
x_reshape[1, 2] 

np.int64(6)

Слично, `x[2]` даје трећи елемент вектора `x`.

Сада ћемо изменити горњи леви елемент `x_reshape`. На наше изненађење, видећемо да је промењен и први елемент `x`!

In [16]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)


x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


Измена `x_reshape` је изменила и `x` зато што ова два објекта заузимају исти простор у меморији.

Видели смо да можемо да изменимо елемент 'array'-а. Да ли можемо да изменимо и 'tuple'?
Испоставља се да не можемо — и покушај доводи до *изузетка* (енгл. 'exception'), односно грешке.

In [17]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2


TypeError: 'tuple' object does not support item assignment

Сада укратко наводимо неке атрибуте 'array'-а који ће нам бити корисни.
Атрибут `shape` садржи димензије 'array'-а; то је увек 'tuple'.
Атрибут `ndim` даје број димензија, а `T` даје транспоновану матрицу.

In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T


Приметите да су три појединачна излаза `(2,3)`, `2` и `array([[5, 4],[2, 5], [3,6]])` сами по себи „упаковани“ као 'tuple'.

Често ћемо примењивати функције на 'array'-е.
На пример, квадратни корен елемената можемо добити функцијом `np.sqrt()`.

In [ ]:
np.sqrt(x)


Елементе можемо и да квадрирамо:

In [ ]:
x**2


Квадратни корен можемо добити и истом нотацијом, подизањем на степен $1/2$ уместо на 2.

In [ ]:
x**0.5


Надаље ћемо ћемо често генерисати случајне податке.
Функција `np.random.normal()` генерише вектор случајних нормалних променљивих.
Више о овој функцији можете видети у помоћи (нпр. `np.random.normal?`).

Прва линија помоћи је `normal(loc=0.0, scale=1.0, size=None)`. То *упутство* нам говори да су аргументи функције `loc`, `scale` и `size`.
То су *keyword* аргументи, што значи да им у позиву можемо навести име (и редослед није битан).
{`Python` подржава и *positional* аргументе, који се не наводе по имену. На пример, погледајте `np.sum?`: аргумент `a` је позициони —
функција подразумева да је први неименовани аргумент 'array' који се сабира. Насупрот томе, `axis` је нпр. 'keyword' аргумент
и њихов редослед у `np.sum()` није битан.}

Подразумевано, `np.random.normal()` генерише нормалне променљиве са средњом вредношћу (`loc`) $0$ и стандардном девијацијом (`scale`) $1$.
Такође, генерише се једна вредност, осим ако не променимо аргумент `size`.

Сада генеришемо 50 независних случајних променљивих из расподеле $N(0,1)$. 

In [ ]:
x = np.random.normal(size=50)
x


Правимо 'array' `y` тако што сваком елементу `x` додамо независну случајну променљиву из $N(50,1)$.

In [ ]:
y = x + np.random.normal(loc=50, scale=1, size=50)

Функција `np.corrcoef()` рачуна корелациону матрицу између `x` и `y`. Ван-дијагонални елементи дају корелацију између `x` и `y`.

In [ ]:
np.corrcoef(x, y)

Ако пратите у сопственом 'Jupyter' notebook-у, вероватно сте приметили да добијате другачије бројеве него овде.
Конкретно, сваки пут када позовемо `np.random.normal()`, добићемо нови случајни резултат, као у примеру испод.

In [ ]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2)) 


Да бисмо обезбедили да наш код даје потпуно исте резултате сваки пут када се покрене, можемо да поставимо *случајно семе* (енгл. 'random seed')
помоћу `np.random.default_rng()`.

Ова функција прима произвољан цео број који бира корисник. Ако поставимо семе пре генерисања случајних бројева, поновно покретање кода ће дати исте вредности.
Објекат `rng` садржи (практично) све методе за генерисање случајних бројева које постоје у `np.random`. Зато, за нормалне податке користимо `rng.normal()`. 

In [ ]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2)) 

Надаље ћемо користити `np.random.default_rng()` кад год радимо са случајним величинама у `numpy`-у.
У принципу, то омогућава да читалац тачно репродукује наведене резултате. Ипак, како се појављују нове верзије `numpy`-а,
могуће су мале разлике добијених израза.

In [ ]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

In [ ]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

Функције `np.mean()`, `np.var()` и `np.std()` се користе за рачунање средње вредности, варијансе и стандардне девијације 'array'-а.
Ове операције су доступне и као методи самог 'array'-а.

In [ ]:
np.sqrt(np.var(y)), np.std(y)

In [ ]:
X = rng.standard_normal((10, 3))
X

Функције `np.mean()`, `np.var()` и `np.std()` можемо применити и по редовима/колонама матрице.
Да бисмо то видели, конструишемо матрицу $10 \times 3$ од $N(0,1)$ случајних променљивих и размотримо рачунање средњих вредности по колонама.

In [ ]:
X.mean(axis=0)

Пошто су 'array'-и уређени по редовима, прва оса (тј. `axis=0`) одговара редовима.
Када проследимо `axis=0` у `mean()` за објекат `X`, добијамо средње вредности по *колонама* (агрегација се врши преко редова).

In [ ]:
X.mean(0)

## Графика

У `Python`-у смо за графику већ користили библиотеку `matplotlib`, а сада ћемо проћи и кроз њене додатне могућности.

Користићемо функцију `subplots()` из `matplotlib.pyplot` да направимо *figure* (слику/платно) и *axes* (осе/подграфик) на који затим исцртавамо податке.
За много више примера графика у `Python`-у, погледајте галерију на: [matplotlib.org/stable/gallery/](https://matplotlib.org/stable/gallery/index.html).

У `matplotlib`-у, график се састоји од *figure* и једног или више *axes*.
На *figure* можете гледати као на „празно платно“ на ком ће бити приказан један или више графика — то је целокупан прозор/излаз за цртање.
*Axes* садржи важне информације о појединачном графику, као што су ознаке $x$ и $y$ осе, наслов, итд.
(Напомена: у `matplotlib`-у реч *axes* није множина од *axis*; *axes* обухвата много више од саме $x$ и $y$ осе.)

Почињемо увозом функције `subplots()` из `matplotlib`. Ову функцију ћемо користити стално када правимо графике.
Она враћа 'tuple' дужине два: објекат *figure* и одговарајући *axes*.
Обично ћемо прослеђивати `figsize` као 'keyword' аргумент.
Када направимо *axes*, правимо први график помоћу његовог метода `plot()`.
За више детаља укуцајте `ax.plot?`.

In [ ]:
from matplotlib.pyplot import subplots
fig, ax = subplots(figsize=(8, 8))
x = rng.standard_normal(100)
y = rng.standard_normal(100)
ax.plot(x, y);


Овде правимо кратку паузу да приметимо да смо 'tuple' дужине два који враћа `subplots()` *распаковали* (енгл. 'unpacked')
у две засебне променљиве: `fig` и `ax`. Распаковање је обично читљивије од следећег, еквивалентног али опширнијег кода.

In [ ]:
output = subplots(figsize=(8, 8))
fig = output[0]
ax = output[1]

Видимо да је претходна ћелија направила линијски график — то је подразумевано понашање.
Да бисмо направили распршени дијаграм (scatterplot), прослеђујемо додатни аргумент у `ax.plot()` који каже да се прикажу кружићи.

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(x, y, 'o');

Различите вредности овог додатног аргумента могу да дају линије различитих боја и различитих стилова (нпр. испрекидана линија).

Као алтернативу, за распршени дијаграм можемо користити и функцију `ax.scatter()`.

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o');

Приметите да смо у горњим примерима последњу линију завршили тачка-запетом (`;`).
То спречава да `ax.plot(x, y)` (или `ax.scatter(x, y)`) испише текстуални излаз у notebook-у, али *не* спречава да се график прикаже.
Ако изоставимо тачка-запету, добијамо и следећи текстуални излаз:

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o')


У наставку ћемо користити тачка-запету на крају линије кад год текстуални излаз није релевантан.

Да бисмо означили осе и наслов графика, користимо методе `set_xlabel()`, `set_ylabel()` и `set_title()` за објекат `ax`.

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o')
ax.set_xlabel("this is the x-axis")
ax.set_ylabel("this is the y-axis")
ax.set_title("Plot of X vs Y");

Пошто имамо и сам објекат *figure* (`fig`), можемо накнадно мењати неке његове особине и поново га приказати.
Овде мењамо величину са `(8, 8)` на `(12, 3)`.

In [ ]:
fig.set_size_inches(12,3)
fig

Понекад желимо да на истом *figure* прикажемо више графика. То постижемо тако што `subplots()` позовемо са додатним аргументима.
Испод правимо мрежу $2 \times 3$ подграфика у 'figure'-у, чија је величина одређена аргументом `figsize`.

У таквим ситуацијама често постоји веза између оса у подграфицима — на пример, сви графици могу имати заједничку $x$-осу.
`subplots()` то може аутоматски да подеси ако проследимо `sharex=True`.

Објекат `axes` који добијамо је 'array' који показује на различите подграфике у 'figure'-у.

In [ ]:
fig, axes = subplots(nrows=2,
                     ncols=3,
                     figsize=(15, 5))

Сада правимо распршени график са `'o'` у другој колони првог реда и распршени график са `'+'` у трећој колони другог реда.

In [ ]:
axes[0,1].plot(x, y, 'o')
axes[1,2].scatter(x, y, marker='+')
fig

Укуцајте `subplots?` да видите више детаља о функцији `subplots()`.

Да бисмо сачували излаз `fig`, позивамо његов метод `savefig()`.
Аргумент `dpi` (dots per inch) одређује резолуцију, односно колико ће график бити велики у пикселима.

In [ ]:
fig.savefig("Figure.png", dpi=400)
fig.savefig("Figure.pdf", dpi=200);


Можемо наставити да мењамо `fig` корак по корак; на пример, променимо опсег $x$-осе, поново сачувамо слику и чак је поново прикажемо.

In [ ]:
axes[0,1].set_xlim([-1,1])
fig.savefig("Figure_updated.jpg")
fig

Сада ћемо направити мало „озбиљније“ графике. Метод `ax.contour()` прави *contour plot* (контурни график)
који представља тродимензионалне податке, слично топографској мапи. Он прима три аргумента:

* вектор `x` вредности (прва димензија),
* вектор `y` вредности (друга димензија),
* матрицу чији елементи одговарају `z` вредностима (трећа димензија) за сваки пар координата `(x, y)`.

Да бисмо направили `x` и `y`, користићемо `np.linspace(a, b, n)`,
који враћа вектор од `n` бројева који почиње од `a` и завршава се на `b`.

In [ ]:
fig, ax = subplots(figsize=(8, 8))
x = np.linspace(-np.pi, np.pi, 50)
y = x
f = np.multiply.outer(np.cos(y), 1 / (1 + x**2))
ax.contour(x, y, f);


Број контура можемо да повећамо тако што додамо више нивоа ('levels') на график.

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.contour(x, y, f, levels=45);

Да бисте прецизније подесили излаз `ax.contour()`, погледајте помоћ укуцавањем `?plt.contour`.

Метод `ax.imshow()` је сличан `ax.contour()`, али прави приказ у бојама, где боја зависи од `z` вредности.
Ово се зове *heatmap* (топлотна мапа) и понекад се користи, на пример, за приказ температуре у временским прогнозама.

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.imshow(f);


## Секвенце и 'slice' нотација

Као што смо видели изнад, функција `np.linspace()` може да се користи за прављење секвенце бројева.

In [ ]:
seq1 = np.linspace(0, 10, 11)
seq1


Функција `np.arange()` враћа секвенцу бројева раздвојених кораком `step`.
Ако `step` није наведен, подразумева се $1$. Направимо секвенцу која почиње од $0$ и иде до $10$.

In [ ]:
seq2 = np.arange(0, 10)
seq2


Зашто се $10$ не појављује у излазу? То је повезано са 'slice' нотацијом у `Python`-у.
'Slice' нотација се користи за индексирање секвенци као што су листе, 'tuple'-ови и 'array'-и.

Рецимо да желимо да узмемо 4–6. (укључујући) карактер из ниске. Узимамо 'slice' помоћу нотације `[3:6]`.

In [ ]:
"hello world"[3:6]

У коду изнад, запис `3:6` је скраћеница за `slice(3,6)` када се користи унутар `[]`.

In [ ]:
"hello world"[slice(3,6)]


Можда сте очекивали да `slice(3,6)` да четврти до седми карактер (подсетник: индексирање у `Python`-у креће од нуле),
али добили смо четврти до шести. То објашњава и зашто `np.arange(0, 10)` даје само целе бројеве од $0$ до $9$.

Погледајте документацију `slice?` за корисне опције при прављењу 'slice'-ова.

## Индексирање података

За почетак, правимо дводимензионални `numpy` 'array'.

In [ ]:
A = np.array(np.arange(16)).reshape((4, 4))
A


Укуцавањем `A[1,2]` добијамо елемент који одговара другом реду и трећој колони. (Као и обично, `Python` индексира од $0$.)

In [ ]:
A[1,2]


Први број после отворене угласте заграде `[` односи се на ред, а други број на колону.

### Индексирање редова, колона и подматрица
Да бисмо изабрали више редова одједном, можемо да проследимо листу која описује избор.
На пример, `[1,3]` ће вратити други и четврти ред:

In [ ]:
A[[1,3]]


Да бисмо изабрали прву и трећу колону, прослеђујемо `[0,2]` као други аргумент у угластим заградама.
У том случају морамо да наведемо први аргумент `:`, који значи „сви редови“.

In [ ]:
A[:,[0,2]]


Сада претпоставимо да желимо подматрицу састављену од другог и четвртог реда, као и прве и треће колоне.
Овде индексирање постаје мало „незгодније“. Природно је да покушамо да листама изаберемо редове и колоне:

In [ ]:
A[[1,3],[0,2]]


Шта се десило? Добили смо једнодимензионални 'array' дужине два, исти као:

In [ ]:
np.array([A[1,0],A[3,2]])


Слично томе, следећи код не успева да извуче подматрицу састављену од другог и четвртог реда и прве, треће и четврте колоне:

In [ ]:
A[[1,3],[0,2,3]]


Видимо шта је пошло неочекивано: када `numpy` добије две листе за индексирање, он их тумачи као парове индекса $(i, j)$ за низ појединачних уноса.
Зато те две листе морају имати исту дужину. Али то није оно што смо желели — ми тражимо подматрицу.

Један једноставан начин је следећи: прво изаберемо редове из `A`, па онда „у лету“ из тог резултата изаберемо колоне.

In [ ]:
A[[1,3]][:,[0,2]]


Постоје и ефикаснији начини да добијемо исти резултат.

Функција погодности (енгл. 'convenience function') `np.ix_()` омогућава да извучемо подматрицу помоћу листи, тако што прави посредни 'mesh' објекат.

In [ ]:
idx = np.ix_([1,3],[0,2,3])
A[idx]


Алтернативно, матрице можемо ефикасно да подскупљујемо помоћу 'slice'-ова.

'Slice' `1:4:2` хвата други и четврти елемент секвенце, док `0:3:2` хвата први и трећи елемент
(трећи елемент у 'slice' запису је величина корака, тј. 'step').

In [ ]:
A[1:4:2,0:3:2]


Зашто можемо директно да извучемо подматрицу помоћу 'slice'-ова, а не помоћу листи?
Зато што су то различити `Python` типови, и `numpy` их третира различито.

'Slice'-ови раде над општим секвенцама (нпр. ниске, листе, 'tuple'-ови), док је коришћење листи за индексирање у `numpy`-у специфичније и ограниченије.

### Буловско ('Boolean') индексирање

У `numpy`-у, *Boolean* је тип који може бити `True` или `False` (често се представља и као $1$ и $0$).
Следећа линија прави вектор нула (као Boolean вредности), дужине једнаке првој димензији матрице `A`.

In [ ]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

Сада два елемента постављамо на `True`.

In [ ]:
keep_rows[[1,3]] = True
keep_rows


Приметите да су елементи `keep_rows`, када их посматрамо као целе бројеве, исти као вредности у `np.array([0,1,0,1])`.
Испод користимо `==` да проверимо једнакост. Када се примени на два 'array'-а, операција `==` се примењује по елементима.

In [ ]:
np.all(keep_rows == np.array([0,1,0,1]))


(Овде је функција `np.all()` проверила да ли су *сви* елементи логичког низа `True`.
Слична функција је `np.any()`, која проверава да ли је *бар један* елемент `True`.)

Међутим, иако су `np.array([0,1,0,1])` и `keep_rows` једнаки по `==`, они индексирају различите скупове редова!
Први пример узима први, други, први и други ред матрице `A`.

In [ ]:
A[np.array([0,1,0,1])]


Насупрот томе, `keep_rows` узима само други и четврти ред `A` — то јест, оне редове за које је Boolean вредност `TRUE`.

In [ ]:
A[keep_rows]


Овај пример показује да `numpy` третира Boolean вредности и целе бројеве различито.

Поново користимо `np.ix_()` да направимо 'mesh' који садржи други и четврти ред, и прву, трећу и четврту колону.
Овог пута функцију примењујемо на Boolean низове, а не на листе.

In [ ]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]


Можемо чак да мешамо листу и Boolean 'array' у аргументима за `np.ix_()`:

In [ ]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]
